var data = [
  {
    "id":"00",
    "title":"Christmas Card 01",
    "url_photo":"image-product/Holiday/Christmas/1.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"01",
    "title":"Christmas Card 02",
    "url_photo":"image-product/Holiday/Christmas/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."

  },
  {
    "id":"02",
    "title":"Christmas Card 03",
    "url_photo":"image-product/Holiday/Christmas/3.jpg",
    "price":"10$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"03",
    "title":"Christmas Card 04",
    "url_photo":"image-product/Holiday/Christmas/4.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"04",
    "title":"Christmas Card 05",
    "url_photo":"image-product/Holiday/Christmas/5.jpg",
    "price":"11$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"05",
    "title":"Father's Day Card 01",
    "url_photo":"image-product/Holiday/Father's Day/1.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"06",
    "title":"Father's Day Card 02",
    "url_photo":"image-product/Holiday/Father's Day/2.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"07",
    "title":"Father's Day Card 03",
    "url_photo":"image-product/Holiday/Father's Day/3.jpg",
    "price":"11$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"08",
    "title":"Father's Day Card 04",
    "url_photo":"image-product/Holiday/Father's Day/4.jpg",
    "price":"9$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"09",
    "title":"Father's Day Card 05",
    "url_photo":"image-product/Holiday/Father's Day/5.jpg",
    "price":"13$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"10",
    "title":"Halloween Card 01",
    "url_photo":"image-product/Holiday/Haloween/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"11",
    "title":"Halloween Card 02",
    "url_photo":"image-product/Holiday/Haloween/2.png",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"12",
    "title":"Halloween Card 03",
    "url_photo":"image-product/Holiday/Haloween/3.jpg",
    "price":"7$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"13",
    "title":"Halloween Card 04",
    "url_photo":"image-product/Holiday/Haloween/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"14",
    "title":"Halloween Card 05",
    "url_photo":"image-product/Holiday/Haloween/5.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"15",
    "title":"International Women's Day Card 01",
    "url_photo":"image-product/Holiday/International Women Day/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"16",
    "title":"International Women's Day Card 02",
    "url_photo":"image-product/Holiday/International Women Day/2.png",
    "price":"9$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"17",
    "title":"International Women's Day Card 03",
    "url_photo":"image-product/Holiday/International Women Day/3.jpg",
    "price":"10$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"18",
    "title":"International Women's Day Card 04",
    "url_photo":"image-product/Holiday/International Women Day/4.jpg",
    "price":"11$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"19",
    "title":"International Women's Day Card 05",
    "url_photo":"image-product/Holiday/International Women Day/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"20",
    "title":"International Women's Day Card 06",
    "url_photo":"image-product/Holiday/International Women Day/6.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"21",
    "title":"International Women's Day Card 07",
    "url_photo":"image-product/Holiday/International Women Day/7.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"22",
    "title":"Mother's Day Card 01",
    "url_photo":"image-product/Holiday/Mother's Day/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"23",
    "title":"Mother's Day Card 02",
    "url_photo":"image-product/Holiday/Mother's Day/2.jpg",
    "price":"9$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"24",
    "title":"Mother's Day Card 03",
    "url_photo":"image-product/Holiday/Mother's Day/3.jpg",
    "price":"10$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"25",
    "title":"Mother's Day Card 04",
    "url_photo":"image-product/Holiday/Mother's Day/4.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"26",
    "title":"Mother's Day Card 05",
    "url_photo":"image-product/Holiday/Mother's Day/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"27",
    "title":"New Year Card 01",
    "url_photo":"image-product/Holiday/New Year/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"28",
    "title":"New Year Card 02",
    "url_photo":"image-product/Holiday/New Year/2.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"29",
    "title":"New Year Card 03",
    "url_photo":"image-product/Holiday/New Year/3.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"30",
    "title":"New Year Card 04",
    "url_photo":"image-product/Holiday/New Year/4.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"31",
    "title":"New Year Card 05",
    "url_photo":"image-product/Holiday/New Year/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"32",
    "title":"Teacher's Day Card 01",
    "url_photo":"image-product/Holiday/Teacher Day/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"33",
    "title":"Teacher's Day Card 02",
    "url_photo":"image-product/Holiday/Teacher Day/2.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"34",
    "title":"Teacher's Day Card 03",
    "url_photo":"image-product/Holiday/Teacher Day/3.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"35",
    "title":"Teacher's Day Card 04",
    "url_photo":"image-product/Holiday/Teacher Day/4.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"36",
    "title":"Teacher's Day Card 05",
    "url_photo":"image-product/Holiday/Teacher Day/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"37",
    "title":"Valentine's Day Card 01",
    "url_photo":"image-product/Holiday/Valentine/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"38",
    "title":"Valentine's Day Card 02",
    "url_photo":"image-product/Holiday/Valentine/2.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"39",
    "title":"Valentine's Day Card 03",
    "url_photo":"image-product/Holiday/Valentine/3.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"40",
    "title":"Valentine's Day Card 04",
    "url_photo":"image-product/Holiday/Valentine/4.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"41",
    "title":"Valentine's Day Card 05",
    "url_photo":"image-product/Holiday/Valentine/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"42",
    "title":"Wedding's Day Card 01",
    "url_photo":"image-product/Wedding/1.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"43",
    "title":"Wedding's Day Card 02",
    "url_photo":"image-product/Wedding/2.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"44",
    "title":"Wedding's Day Card 03",
    "url_photo":"image-product/Wedding/3.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"45",
    "title":"Wedding's Day Card 04",
    "url_photo":"image-product/Wedding/4.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"46",
    "title":"Wedding's Day Card 05",
    "url_photo":"image-product/Wedding/5.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"47",
    "title":"Wedding's Day Card 05",
    "url_photo":"image-product/Wedding/6.jpg",
    "price":"8$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"48",
    "title":"Birthday Card 01",
    "url_photo":"image-product/Greeting/Birthday/1.jpg",
    "price":"12$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"49",
    "title":"Birthday Card 02",
    "url_photo":"image-product/Greeting/Birthday/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"50",
    "title":"Birthday Card 03",
    "url_photo":"image-product/Greeting/Birthday/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"51",
    "title":"Birthday Card 04",
    "url_photo":"image-product/Greeting/Birthday/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"52",
    "title":"Birthday Card 05",
    "url_photo":"image-product/Greeting/Birthday/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"53",
    "title":"Congratulation Card 01",
    "url_photo":"image-product/Greeting/Congratulation/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"54",
    "title":"Congratulation Card 02",
    "url_photo":"image-product/Greeting/Congratulation/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"55",
    "title":"Congratulation Card 03",
    "url_photo":"image-product/Greeting/Congratulation/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"56",
    "title":"Congratulation Card 04",
    "url_photo":"image-product/Greeting/Congratulation/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"57",
    "title":"Congratulation Card 05",
    "url_photo":"image-product/Greeting/Congratulation/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"58",
    "title":"Family Card 01",
    "url_photo":"image-product/Greeting/Family/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"59",
    "title":"Family Card 02",
    "url_photo":"image-product/Greeting/Family/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"60",
    "title":"Family Card 03",
    "url_photo":"image-product/Greeting/Family/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"61",
    "title":"Family Card 04",
    "url_photo":"image-product/Greeting/Family/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"62",
    "title":"Family Card 05",
    "url_photo":"image-product/Greeting/Family/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"63",
    "title":"Friend Card 01",
    "url_photo":"image-product/Greeting/Friend/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"64",
    "title":"Friend Card 02",
    "url_photo":"image-product/Greeting/Friend/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"65",
    "title":"Friend Card 03",
    "url_photo":"image-product/Greeting/Friend/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"66",
    "title":"Friend Card 04",
    "url_photo":"image-product/Greeting/Friend/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"67",
    "title":"Friend Card 05",
    "url_photo":"image-product/Greeting/Friend/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"68",
    "title":"Goodbye and Goodluck Card 01",
    "url_photo":"image-product/Greeting/Goodbye and Goodluck/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"69",
    "title":"Goodbye and Goodluck Card 02",
    "url_photo":"image-product/Greeting/Goodbye and Goodluck/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"70",
    "title":"Goodbye and Goodluck Card 03",
    "url_photo":"image-product/Greeting/Goodbye and Goodluck/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"71",
    "title":"Goodbye and Goodluck Card 04",
    "url_photo":"image-product/Greeting/Goodbye and Goodluck/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"72",
    "title":"Goodbye and Goodluck Card 05",
    "url_photo":"image-product/Greeting/Goodbye and Goodluck/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"73",
    "title":"Love Card 01",
    "url_photo":"image-product/Greeting/Love/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"74",
    "title":"Love Card 02",
    "url_photo":"image-product/Greeting/Love/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"75",
    "title":"Love Card 03",
    "url_photo":"image-product/Greeting/Love/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"76",
    "title":"Love Card 04",
    "url_photo":"image-product/Greeting/Love/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"77",
    "title":"Love Card 05",
    "url_photo":"image-product/Greeting/Love/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"78",
    "title":"Thank you Card 01",
    "url_photo":"image-product/Greeting/Thank You/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"79",
    "title":"Thank you Card 02",
    "url_photo":"image-product/Greeting/Thank You/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"80",
    "title":"Thank you Card 03",
    "url_photo":"image-product/Greeting/Thank You/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"81",
    "title":"Thank you Card 04",
    "url_photo":"image-product/Greeting/Thank You/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"82",
    "title":"Thank you Card 05",
    "url_photo":"image-product/Greeting/Thank You/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"83",
    "title":"Handmade Card 01",
    "url_photo":"image-product/Handmade/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"84",
    "title":"Handmade Card 02",
    "url_photo":"image-product/Handmade/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"85",
    "title":"Handmade Card 03",
    "url_photo":"image-product/Handmade/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"86",
    "title":"Handmade Card 04",
    "url_photo":"image-product/Handmade/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"87",
    "title":"Handmade Card 05",
    "url_photo":"image-product/Handmade/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"88",
    "title":"Handmade Card 06",
    "url_photo":"image-product/Handmade/6.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"89",
    "title":"Color Connect Card 01",
    "url_photo":"image-product/Brand/Color Connect/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"90",
    "title":"Color Connect Card 02",
    "url_photo":"image-product/Brand/Color Connect/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"91",
    "title":"Color Connect Card 03",
    "url_photo":"image-product/Brand/Color Connect/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"92",
    "title":"Color Connect Card 04",
    "url_photo":"image-product/Brand/Color Connect/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"93",
    "title":"Color Connect Card 05",
    "url_photo":"image-product/Brand/Color Connect/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"94",
    "title":"Consola Card 01",
    "url_photo":"image-product/Brand/Consola/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"95",
    "title":"Consola Card 02",
    "url_photo":"image-product/Brand/Consola/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"96",
    "title":"Consola Card 03",
    "url_photo":"image-product/Brand/Consola/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"97",
    "title":"Consola Card 04",
    "url_photo":"image-product/Brand/Consola/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"98",
    "title":"Consola Card 05",
    "url_photo":"image-product/Brand/Consola/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"99",
    "title":"Hokey Joke Card 01",
    "url_photo":"image-product/Brand/Hokey Joke/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"100",
    "title":"Hokey Joke Card 02",
    "url_photo":"image-product/Brand/Hokey Joke/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"101",
    "title":"Hokey Joke Card 03",
    "url_photo":"image-product/Brand/Hokey Joke/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"102",
    "title":"Hokey Joke Card 04",
    "url_photo":"image-product/Brand/Hokey Joke/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"103",
    "title":"Hokey Joke Card 05",
    "url_photo":"image-product/Brand/Hokey Joke/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"104",
    "title":"Nannie Grace Card 01",
    "url_photo":"image-product/Brand/Nannie Grace/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"105",
    "title":"Nannie Grace Card 02",
    "url_photo":"image-product/Brand/Nannie Grace/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"106",
    "title":"Nannie Grace Card 03",
    "url_photo":"image-product/Brand/Nannie Grace/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"107",
    "title":"Nannie Grace Card 04",
    "url_photo":"image-product/Brand/Nannie Grace/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"108",
    "title":"Nannie Grace Card 05",
    "url_photo":"image-product/Brand/Nannie Grace/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"109",
    "title":"PrintMate Card 01",
    "url_photo":"image-product/Brand/PrintMate/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"110",
    "title":"PrintMate Card 02",
    "url_photo":"image-product/Brand/PrintMate/2.png",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"111",
    "title":"PrintMate Card 03",
    "url_photo":"image-product/Brand/PrintMate/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"112",
    "title":"PrintMate Card 04",
    "url_photo":"image-product/Brand/PrintMate/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"113",
    "title":"PrintMate Card 05",
    "url_photo":"image-product/Brand/PrintMate/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"114",
    "title":"The Flower Basket Card 01",
    "url_photo":"image-product/Brand/The Flower Basket/1.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"115",
    "title":"The Flower Basket Card 02",
    "url_photo":"image-product/Brand/The Flower Basket/2.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"116",
    "title":"The Flower Basket Card 03",
    "url_photo":"image-product/Brand/The Flower Basket/3.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"117",
    "title":"The Flower Basket Card 04",
    "url_photo":"image-product/Brand/The Flower Basket/4.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
  {
    "id":"118",
    "title":"The Flower Basket Card 05",
    "url_photo":"image-product/Brand/The Flower Basket/5.jpg",
    "price":"14$",
    "SPECIFICATIONS1":"Height: 26 cm X Length: 21 cm",
    "SPECIFICATIONS2":"Freeship with 3 product.",
    "DESCRIPTION1":"Let the festive time be magical and spectacular for your near and dear ones with this beautiful greeting card.",
    "DESCRIPTION2":"This greeting card when opened gets beautifully lit and plays a soothing music, making it a perfect pick to convey your good wishes for them on the joyful occasion.",
    "DESCRIPTION3":"An elegant and beautiful bokeh lights Archies anniversary card that has words of love to bless a beautiful couple on their wedding anniversary."
  },
];